# Generated by Django 2.2.6 on 2019-10-23 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0075_cable_devices'),
        ('ipphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_templates', to='dcim.DeviceType')),
            ],
            options={
                'ordering': ['device_type', 'name'],
            },
        ),
    ]
