# Generated by Django 2.2.6 on 2019-10-09 15:13

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0075_cable_devices'),
        ('extras', '0025_objectchange_time_index'),
        ('ipphone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='interface',
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dcim.Device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['device', 'name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.AddField(
            model_name='extension',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='ipphone.Line'),
        ),
    ]
