# Generated by Django 2.2.6 on 2019-10-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipphone', '0002_auto_20191004_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='ipphonepartition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ipphone.IPPhonePartition'),
        ),
    ]
